// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxdsBret1GeFZMBi2Bpk_U84ZszVxA0Fw',
    appId: '1:482308819172:web:b0edea25bfd188df3684f1',
    messagingSenderId: '482308819172',
    projectId: 'notificationpush-e237a',
    authDomain: 'notificationpush-e237a.firebaseapp.com',
    storageBucket: 'notificationpush-e237a.appspot.com',
    measurementId: 'G-C7HQJ0CFLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1BtOEllEu9KvGX7u5sEj3v3CqX_f1mE',
    appId: '1:482308819172:android:7bfee718a1e7025e3684f1',
    messagingSenderId: '482308819172',
    projectId: 'notificationpush-e237a',
    storageBucket: 'notificationpush-e237a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBHmq__zABXaaIftpqDarI0YSOI31vJ0',
    appId: '1:482308819172:ios:454d9e03d0a6f45a3684f1',
    messagingSenderId: '482308819172',
    projectId: 'notificationpush-e237a',
    storageBucket: 'notificationpush-e237a.appspot.com',
    iosClientId: '482308819172-rsqmkk30s1olq5q92md4c7kgu8m5h4vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBHmq__zABXaaIftpqDarI0YSOI31vJ0',
    appId: '1:482308819172:ios:0389ac9cc727aeb43684f1',
    messagingSenderId: '482308819172',
    projectId: 'notificationpush-e237a',
    storageBucket: 'notificationpush-e237a.appspot.com',
    iosClientId: '482308819172-req9crvgmvhuermno6tpogb19k8p18et.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification.RunnerTests',
  );
}
